### ISSUE TITLE
DDNS Update Failed

### ISSUE THREAD

**Issue by gui-li** [dvershinin/cloudflareddns#5]
I successfully install your module in the lazier way without virtualenv and I did found cloudflareddns under /bin. However, when I tried to add a Cloudflare ddns in GUI, it failed and show message "Failed to connect to the server. Please check the network connection of the server.". Anyway, I tried to manually execute this script with --email and other parameters, it succeeded smoothly. So I set it as schedule task to run every hour. Could you help me figure out what's going wrong?

**Comment by dvershinin** [comment]
Hi,

Can you run `cat /etc/ddns_provider.conf` and post the output.

You seem to be using email+API key. Have you put email and key in respective fields?

**Comment by gui-li** [comment]
Ouput:
[USER_Cloudflare]
        modulepath=/bin/cloudflareddns-syno
                queryurl=https://www.cloudflare.com/

Yes, I do place email and key in the right places.

**Comment by gui-li** [comment]
When I tried to run cloudflareddns directly in CLI, I got the following error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/CloudflareDDNS/lib/python2.7/site-packages/cloudflareddns/cloudflareddns.py", line 163, in updateRecord
    res = update(hostname, ip, ttl)
  File "/usr/local/CloudflareDDNS/lib/python2.7/site-packages/cloudflareddns/cloudflareddns.py", line 79, in update
    cf = CloudFlare.CloudFlare()
  File "/usr/local/CloudflareDDNS/lib/python2.7/site-packages/CloudFlare/cloudflare.py", line 864, in __init__
    raise CloudFlareAPIError(0, 'profile/configuration read error')
CloudFlare.exceptions.CloudFlareAPIError: profile/configuration read error

My ~/.cloudflare/cloudflare.cfg:
[CloudFlare]
email = x
token = MyAPIToken

My ~/.bashrc:
export CF_API_EMAIL="x"
export CF_API_KEY=MyAPIToken

**Comment by gui-li** [comment]
> Ouput:
> [USER_Cloudflare]
> modulepath=/bin/cloudflareddns-syno
> queryurl=https://www.cloudflare.com/
> 
> Yes, I do place email and key in the right places.

By the way, I have changed the way I install to virtualenv, so the contents now are:

[USER_Cloudflare]
        modulepath=/usr/local/CloudflareDDNS/bin/cloudflareddns-syno
        queryurl=https://www.cloudflare.com/

**Comment by dvershinin** [comment]
Do you actually put `x`? The `x` is ok to go to Synology GUI as long as you're using API token (not key). 

See [here](https://github.com/cloudflare/python-cloudflare#using-configuration-file-to-store-email-and-keys) on format of `cloudflare.cfg`. If using email+api key, then you should have an actual email + key.
And if using API *token*, then you will not have `email` field at all in your configs, just `token`.

Also having those things in bashrc is unneeded (unless you have other programs relying on those env vars).

**Comment by gui-li** [comment]
Sure, I did tried either API token and global API option, but neither one of them works.
However, I have resorted to my Ubuntu server responsible for updating the DDNS.

**Comment by dvershinin** [comment]
Just looking at the Cloudflare package code, the `CloudFlare.exceptions.CloudFlareAPIError: profile/configuration read error` seems to be with failure to parse the `.ini` file in some way.  So maybe there's a problem with its encoding/formatting... You may want to raise the extra issue with them if you are sure that your config file is correct.
