### ISSUE TITLE
Unexpected keyword argument 'cfEmail'

### ISSUE THREAD

**Issue by mettamatt** [dvershinin/cloudflareddns#6]
On my Synology NAS, when I run `cloudflareddns-syno` from the command line I get an error. Note that "api-token, hostname, and IP" are replaced with the values for my setup. 

`/bin/cloudflareddns-syno x api-token hostname IP`

I receive the following error:

```
Traceback (most recent call last):
  File "/bin/cloudflareddns-syno", line 8, in <module>
    sys.exit(syno())
  File "/usr/lib/python2.7/site-packages/cloudflareddns/cloudflareddns.py", line 229, in syno
    cfKey=sys.argv[4]
TypeError: update() got an unexpected keyword argument 'cfEmail'
```

And the DSM GUI fails with an unknown error. 

When I use the same variables and call `cloudflareddns`, the DDNS updates as expected. 

`/bin/cloudflareddns --key api-token --hostname hostname --verbose`

```
DEBUG: Verbose output.
DEBUG: Getting public IP from an external service
DEBUG: Starting new HTTPS connection (1): ident.me:443
DEBUG: https://ident.me:443 "GET / HTTP/1.1" 200 14
DEBUG: Updating foo to IP
DEBUG: Zone domain of hostname is foo
DEBUG: Starting new HTTPS connection (1): api.cloudflare.com:443
DEBUG: https://api.cloudflare.com:443 "GET /client/v4/zones?name=foo HTTP/1.1" 200 None
DEBUG: Zone ID is xxx
DEBUG: https://api.cloudflare.com:443 "GET /client/v4/zones/xxx/dns_records?type=A&name=foo&match=all HTTP/1.1" 200 None
INFO: UNCHANGED: foo == IP
```

Any ideas or debugging tips?

**Comment by dvershinin** [comment]
Please try updating  via `pip install cloudflareddns -U` (inside virtualenv, if you used it).
The new fixed version is released.
