### ISSUE TITLE
Permissions error when running "curl https://bootstrap.pypa.io/get-pip.py | python" on synology NAS

### ISSUE THREAD

**Issue by Wizkid288** [dvershinin/cloudflareddns#7]
This is what I see when I enter "curl https://bootstrap.pypa.io/get-pip.py | python"
curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1825k  100 1825k    0     0  5668k      0 --:--:-- --:--:-- --:--:-- 5668k
/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting pip
  Using cached pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
Collecting wheel
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, wheel
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/pip-20.1.1.dist-info'
Check the permissions.

I am also noob :)

**Comment by dvershinin** [comment]
You need to be logged in as the `root` user. See [here](https://www.synology.com/tr-tr/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet).
Just ensure that the SSH prompt shows that you are `root`.

**Comment by Wizkid288** [comment]
wow im dumb. everything works now. Thank you :)

**Comment by sonicjack8x** [comment]
Whatatatatatattatatata
